penalty : 100.0
reward_parameters:
  fibre_costs: 1.20 # € per kg
  energy_costs: 0.28 # € per kWh
  selling_price: 2.50 # € per sqm
  floor_quality_weight: 10.0
reward_range:
  lower: -2000
  upper: 10000
output_bounds:
  areaWeightLane1:
    lower: 200.0
    upper: 500.0
  areaWeightLane2:
    lower: 200.0
    upper: 500.0
  areaWeightLane3:
    lower: 200.0
    upper: 500.0
  tensileStrengthCD:
    lower: 650.0
  tensileStrengthMD:
    lower: 400.0


