action_space:
  CardDeliveryWeightPerArea:
    low: -100.0
    high: 100.0
  Cross-lapperLayersCount:
    low: -100.0
    high: 100.0
  Needleloom1DraftRatio:
    low: -100.0
    high: 100.0
  ProductionSpeedSetpoint:
    low:  0.0
    high: 100.0
  Cross-lapperProfiling:
    low: -1000.0
    high: 1000.0
  DrawFrameDraftRatio:
    low: -1000.0
    high: 1000.0
  CardMassThroughputSetpoint:
    low: -10000.0
    high: 10000.0
  Needleloom1FeedPerStroke:
    low: -100.0
    high: 100.0
  Needleloom2NeedlepunchDepth:
    low: -100.0
    high: 100.0
  v_PreRoll:
    low: -1000.0
    high: 1000.0
  v_MainCylinder:
    low: -10000.0
    high: 10000.0
  v_WorkerMain:
    low: -1000.0
    high: 1000.0
  v_StripperMain:
    low: -1000.0
    high: 1000.0
  v_WorkerPre:
    low: -10000.0
    high: 10000.0
  v_StripperPre:
    low: -1000.0
    high: 1000.0
observation_space:
  FeederDeliverySpeed:
    low: -10000.0
    high: 10000.0
  ProductB:
    low: -10000.0
    high: 10000.0
  ProductWidth:
    low: -10000.0
    high: 10000.0
  SmileEffectStrength:
    low: -10000.0
    high: 10000.0
  Needleloom2DraftRatio:
    low: -10000.0
    high: 10000.0
  Needleloom1DraftRatioIntake:
    low: -10000.0
    high: 10000.0
  Needleloom2FeedPerStroke:
    low: -10000.0
    high: 10000.0
  CardDeliveryWeightPerArea:
    low: -100.0
    high: 100.0
  Cross-lapperLayersCount:
    low: -100.0
    high: 100.0
  Needleloom1DraftRatio:
    low: -100.0
    high: 100.0
  Cross-lapperProfiling:
    low: -1000.0
    high: 1000.0
  DrawFrameDraftRatio:
    low: -1000.0
    high: 1000.0
  ProductionSpeedSetpoint:
    low:  0.0
    high: 100.0
  CardMassThroughputSetpoint:
    low: -10000.0
    high: 10000.0
  Needleloom1FeedPerStroke:
    low: -100.0
    high: 100.0
  Needleloom2NeedlepunchDepth:
    low: -100.0
    high: 100.0
  v_PreRoll:
    low: -1000.0
    high: 1000.0
  v_MainCylinder:
    low: -10000.0
    high: 10000.0
  v_WorkerMain:
    low: -1000.0
    high: 1000.0
  v_StripperMain:
    low: -1000.0
    high: 1000.0
  v_WorkerPre:
    low: -10000.0
    high: 10000.0
  v_StripperPre:
    low: -1000.0
    high: 1000.0
  LineSpeed:
    low: 0.0
    high: 100.0
  AreaWeightLane1:
    low: -100.0
    high: 1000.0
  AreaWeightLane2:
    low: -100.0
    high: 1000.0
  AreaWeightLane3:
    low: -100.0
    high: 1000.0
  LinePowerConsumption:
    low: -100.0
    high: 1000.0
  TensileStrengthCD:
    low: -100.0
    high: 10000.0
  TensileStrengthMD:
    low: -100.0
    high: 10000.0
  CardWebUnevenness:
    low: -100.0
    high: 100.0
