reward:
  requirements :
    bLower : 30.0
    bUpper : 100.0
  penalty : 1.0
  fibreCosts : 276.00
  weights :
    output1 : 10.0
    output2 : 20.0
env:
  actionParams : 
    input1 : 
      low : 0.0
      high : 100.0
    input2 :
      low : 20.0
      high : 80.0
    input3 :
      low : 10.0
      high : 99.0
    list : ['input1', 'input2', 'input3']
  stateParams : 
    - sP1 : 0.3
    - sP2 : 999.0
  observationParams : 
    output1 :
      low : 0.0
      high : 999.0
    output2 :
      low : 0.0
      high : 8.8
    list : ['output1', 'output2']
  actorConstraints : 
    - aC1 : 0.0
    - aC2 : 8.9
  productionScenario : 
    - pS1 : 5.5
    - pS2 : 7.4
  stepsUntilLabDataAvailable : 100
  maxSteps : 1000
  initialState :
    input1 : 5.0
    input2 : 6.0
    input3 : 7.0
experimentTracker:
  metrics : ['reward', 'action', 'observation']
scenarioManager:
  disturbanceSetting : 
    dist1 : 1.0
    dist2 : 2.0
  fibreSetting :
    fibre3: 3.0
    fibre4: 4.0
safety :
  constraints : 
    weight : 100.0
    speed1 : 100.0
    speed2 : 90.0
