env:
  usedControls: ["Ishikawa_LayersCount", "Ishikawa_DraftRatioNeedleloom1Intake", "Ishikawa_DraftRatioNeedleloom",
                       "Ishikawa_CardMassThroughputSetpoint", "v_Vorreisser", "v_Arbeiter_HT", "v_Wender_HT",
                       "v_Arbeiter_VR", "v_Wender_VR", "v_Abnehmer"]
  usedDisturbances: ["Ishikawa_WeightPerAreaCardDelivery", "mean_cylinder_worker"]
  initialControls:
    Ishikawa_LayersCount: 0.5
    Ishikawa_DraftRatioNeedleloom1Intake: 0.5
    Ishikawa_DraftRatioNeedleloom: 0.5
    Ishikawa_CardMassThroughputSetpoint: 0.5
    v_Vorreisser: 0.5
    v_Arbeiter_HT: 0.5
    v_Wender_HT: 0.5
    v_Arbeiter_VR: 0.5
    v_Wender_VR: 0.5
    v_Abnehmer: 0.5
  initialDisturbances:
    Ishikawa_WeightPerAreaCardDelivery: 1.0
    mean_cylinder_worker: 1.0
  actionType : 0 # 0 for relative | 1 for absolute
  actionSpace:
    Ishikawa_LayersCount:
      low: -100.0
      high: 100.0
    Ishikawa_DraftRatioNeedleloom1Intake:
      low: -100.0
      high: 100.0
    Ishikawa_DraftRatioNeedleloom:
      low: -100.0
      high: 100.0
    Ishikawa_CardMassThroughputSetpoint:
      low: -100.0
      high: 100.0
    v_Vorreisser:
      low: -100.0
      high: 100.0
    v_Arbeiter_HT:
      low: -100.0
      high: 100.0
    v_Wender_HT:
      low: -100.0
      high: 100.0
    v_Arbeiter_VR:
      low: -100.0
      high: 100.0
    v_Wender_VR:
      low: -100.0
      high: 100.0
    v_Abnehmer:
      low: -100.0
      high: 100.0
  observationSpace:
    min_area_weight:
      low: -100.0
      high: 100.0
    unevenness_card_web:
      low: -100.0
      high: 100.0
safetyWrapper:
    simpleControlBounds:
        Ishikawa_LayersCount:
            lower: 0.1
            upper: 0.9
        Ishikawa_DraftRatioNeedleloom1Intake:
            lower: 0.1
            upper: 0.9
        Ishikawa_DraftRatioNeedleloom:
            lower: 0.1
            upper: 0.9
    complexConstraints:
        addMin: 2.0
        addMax: 8.0
modelWrapper:
  pathToModels: C:\Users\Luisito\Desktop\adanowo-simulator\models
  usedModels: ["min_area_weight", "unevenness_card_web"]
  rescaleY: True
  latent: False
reward:
  penalty : 10.0
  simpleOutputBounds:
    lower:
        min_area_weight: 0.0
        unevenness_card_web: 0.0
    upper:
        unevenness_card_web: 20.0
  complexConstraints:
    multMin: 0.0
    multMax: 200.0
  fibreSettings:
    fibreCosts: 1.0
  weights:
    w1: 0.1
    w2: 0.5
experimentTracker:
  project: "adanowo-simulator"

