actions_are_relative: True
initial_controls:
  CardDeliveryWeightPerArea: 63.7 # g per sqm
  Cross-lapperLayersCount: 6.0 # -
  Needleloom1DraftRatio: 43.0 # percent
  Cross-lapperProfiling: 0.0 # percent
  DrawFrameDraftRatio: 44.7 # percent
  CardMassThroughputSetpoint: 715.6 # kg per h
  Needleloom1FeedPerStroke: 10.5 # mm per stroke
  Needleloom2NeedlepunchDepth: 10.8 # mm
  v_PreRoll: 215.0 # m per min
  v_MainCylinder: 805.0 # m per min
  v_WorkerMain: 40.3 # m per min
  v_StripperMain: 160.0 # m per min
  v_WorkerPre: 18.0 # m per min
  v_StripperPre: 65.0 # m per min
path_to_dependent_variable_calculations: # use default if not a valid path
dependent_variable_calculations:
  LineSpeed: lineSpeedCalculation # m per min
control_bounds:
  CardDeliveryWeightPerArea:
    lower: 45
    upper: 85
  Cross-lapperLayersCount:
    lower: 2.0
    upper: 13.0
  Needleloom1DraftRatio:
    lower: 25
    upper: 65
  Cross-lapperProfiling:
    lower: 0
    upper: 40
  DrawFrameDraftRatio:
    lower: 20
    upper: 90
  CardMassThroughputSetpoint:
    lower: 350
    upper: 1100
  Needleloom1FeedPerStroke:
    lower: 9
    upper: 15
  Needleloom2NeedlepunchDepth:
    lower: 9
    upper: 14
  v_PreRoll:
    lower: 180
    upper: 400
  v_MainCylinder:
    lower: 400
    upper: 1400
  v_WorkerMain:
    lower: 20
    upper: 130
  v_StripperMain:
    lower: 45
    upper: 250
  v_WorkerPre:
    lower: 15
    upper: 27
  v_StripperPre:
    lower: 40
    upper: 85
dependent_variable_bounds:
  LineSpeed:
    lower: 0
    upper: 11
