path_to_reward_functions: C:/Users/luisk/Desktop/adanowo-simulator/adanowo_simulator/reward_functions
reward_function: baseline_reward
penalty : 100.0
reward_parameters:
  fibre_costs: 1.20 # € per kg
  energy_costs: 0.28 # € per kWh
  selling_price: 2.50 # € per sqm
  floor_quality_weight: 10.0
reward_range:
  lower: -2000
  upper: 10000
output_bounds:
  lower:
      areaWeightLane1: 200.0
      areaWeightLane2: 200.0
      areaWeightLane3: 200.0
      tensileStrengthCD: 650.0
      tensileStrengthMD: 400.0
      lineSpeed: 0.0
  upper:
      areaWeightLane1: 500.0
      areaWeightLane2: 500.0
      areaWeightLane3: 500.0
      lineSpeed: 11.0


