disturbances:
  FeederDeliverySpeed: 9.6
  ProductB: 0.0
  ProductWidth: 4.8
  SmileEffectStrength: 5.0
  Needleloom2DraftRatio: 23.0
  Needleloom1DraftRatioIntake: 10.0
  Needleloom2FeedPerStroke: 11.25