used_setpoints:
  - v_PreRoll # m per min
  - v_MainCylinder # m per min
  - v_WorkerMain # m per min
  - v_WorkerPre # m per min
  - CardDeliveryWeightPerArea # g per sqm
  - CardDeliverySpeed # m per min
  - Cross-lapperProfiling # percent
  - Cross-lapperLayersCount
  - DrawFrameDraftRatio # percent
  - NeedleloomFeedPerStroke # mm per stroke
  - NeedleloomDraftRatio # percent
used_dependent_variable_setpoints:
  - CardMassThroughput # kg per h
used_disturbances:
  - NeedleloomDraftRatioIntake # percent
  - ProductWidth # m
  - Cross-lapperOverlap # mm
  - ProductionSpeed # m per min
used_outputs:
  - AreaWeightLane1 # g per sqm
  - AreaWeightLane2 # g per sqm
  - AreaWeightLane3 # g per sqm
  - LinePowerConsumption # W
  - TensileStrengthCD # N
  - TensileStrengthMD # N
  - NonwovenUnevenness # -
observations:
  - disturbances
  - setpoints
  - outputs
