used_setpoints:
  - CardDeliveryWeightPerArea # g per sqm
  - Cross-lapperLayersCount
  - NeedleloomDraftRatio # percent
  - DrawFrameDraftRatio # percent
  - Cross-lapperProfiling # percent
  - NeedleloomFeedPerStroke # mm per stroke
  - CardMassThroughputSetpoint # kg per h
  - v_PreRoll # m per min
  - v_MainCylinder # m per min
  - v_WorkerMain # m per min
  - v_StripperMain # m per min
  - v_WorkerPre # m per min
  - v_StripperPre # m per min
used_dependent_variable_setpoints:
used_disturbances:
  - NeedleloomDraftRatioIntake # percent
#  - ProductWidth # m
used_outputs:
  - areaWeight # g per sqm
#  - AreaWeightLane2 # g per sqm
#  - AreaWeightLane3 # g per sqm
#  - LinePowerConsumption # W
  - Energy
  - TensileStrengthCD # N
  - TensileStrengthMD # N
  - CardWebUnevenness # -
observations:
  - disturbances
  - setpoints
  - outputs
