used_primary_controls:
  # weight per area
  - CardDeliveryWeightPerArea # g per sqm
  - Cross-lapperLayersCount
  - Needleloom1DraftRatio # percent
  - Cross-lapperProfiling # percent
  - DrawFrameDraftRatio # percent
  # power consumption (additional)
  - CardMassThroughputSetpoint # kg per h
  - Needleloom1FeedPerStroke # mm per stroke
  # tensile strength CD (additional)
  # tensile strength MD (additional)
  - Needleloom2NeedlepunchDepth # mm
  # evenness card floor (additional)
  - v_PreRoll # m per min
  - v_MainCylinder # m per min
  - v_WorkerMain # m per min
  - v_StripperMain # m per min
  - v_WorkerPre # m per min
  - v_StripperPre # m per min
used_secondary_controls:
  - LineSpeed # m per min
used_disturbances:
  - FeederDeliverySpeed # m per min
  - ProductB # bool
  - ProductWidth # m
  - SmileEffectStrength # g per sqm
  - Needleloom2DraftRatio # percent
  - Needleloom1DraftRatioIntake # percent
  - Needleloom2FeedPerStroke # mm per stroke
used_outputs:
  - AreaWeightLane1 # g per sqm
  - AreaWeightLane2 # g per sqm
  - AreaWeightLane3 # g per sqm
  - LinePowerConsumption # W
  - TensileStrengthCD # N
  - TensileStrengthMD # N
  - CardWebUnevenness # -
