defaults:
  - env_setup: baseline
  - disturbance_setup: baseline
  - action_setup: baseline
  - output_setup: baseline
  - objective_setup: baseline
  - scenario_setup: baseline
  - gym_setup: baseline
  - _self_
tracking_enabled: true
wandb_settings:
  project: adanowo-simulator
  mode: online
physical_execution: false
parallel_execution: true
num_experiment_steps: 100