server_url: opc.tcp://localhost:4840/freeopcua/server/
control_state_node_id: # Node id of the control state
  namespace_index: 2
  identifier: 63 # 31 for old server
agent_input_node:
  namespace_index: 2
  identifier: 2
agent_output_node:
  namespace_index: 2
  identifier: 3
agent_state_values:
  invalid: 0
  valid: 1
  accepted: 2
  rejected_card: 3
  rejected_other: 4
polling_interval: 2 # Polling interval in seconds
output_models:
  - AreaWeightLane1
  - AreaWeightLane2
  - AreaWeightLane3
  - LinePowerConsumption
  - TensileStrengthCD
  - TensileStrengthMD
  - NonwovenUnevenness
outputs_always_available:
  - LinePowerConsumption
  - NonwovenUnevenness
user_feedback_key: UserFeedback
