path_to_output_models: # use default if not a valid path
output_models:
  AreaWeightLane1: areaWeightLane1Model
  AreaWeightLane2: areaWeightLane2Model
  AreaWeightLane3: areaWeightLane3Model
  LinePowerConsumption: linePowerConsumptionModel
  TensileStrengthCD: tensileStrengthCDModel
  TensileStrengthMD: tensileStrengthMDModel
  CardWebUnevenness: cardWebUnevennessModel
