server_url: opc.tcp://localhost:4840/freeopcua/server/
parent_node_id: test # Parent node of the output and state values at server
control_state_node_id: # Node id of the control state
  namespace_index: 2
  identifier: 31
agent_state_values:
  invalid: 0
  accepted: 1
  rejected: 2
polling_interval: 2 # Polling interval in seconds
output_models:
  AreaWeightLane1: areaWeightLane1Model
  AreaWeightLane2: areaWeightLane2Model
  AreaWeightLane3: areaWeightLane3Model
  LinePowerConsumption: linePowerConsumptionModel
  TensileStrengthCD: tensileStrengthCDModel
  TensileStrengthMD: tensileStrengthMDModel
  CardWebUnevenness: cardWebUnevennessModel
