used_controls:
  - Ishikawa_LayersCount
  - Ishikawa_DraftRatioNeedleloom1Intake
  - Ishikawa_DraftRatioNeedleloom
  - Ishikawa_CardMassThroughputSetpoint
  - v_Vorreisser
  - v_Arbeiter_HT
  - v_Wender_HT
  - v_Arbeiter_VR
  - v_Wender_VR
  - v_Abnehmer
  - M_015_NM1_Vorschub_mm_H
  - D_018_SW_Gesamtverzug_Perc
used_disturbances:
  - Ishikawa_WeightPerAreaCardDelivery
  - mean_cylinder_worker
used_outputs:
  - min_area_weight
  - unevenness_card_web
  - tensile_strength_CD
path_to_models: ./models
output_models:
  min_area_weight: min_area_weight
  unevenness_card_web: unevenness_card_web
  tensile_strength_CD: tensile_strength_CD

action_space:
  Ishikawa_LayersCount:
    low:  0.0
    high: 100.0
  Ishikawa_DraftRatioNeedleloom1Intake:
    low:  0.0
    high: 200.0
  Ishikawa_DraftRatioNeedleloom:
    low:  0.0
    high: 200.0
  Ishikawa_CardMassThroughputSetpoint:
    low: -100.0
    high: 100.0
  v_Vorreisser:
    low: -100.0
    high: 100.0
  v_Arbeiter_HT:
    low: -100.0
    high: 100.0
  v_Wender_HT:
    low: -100.0
    high: 100.0
  v_Arbeiter_VR:
    low: -100.0
    high: 100.0
  v_Wender_VR:
    low: -100.0
    high: 100.0
  v_Abnehmer:
    low: -100.0
    high: 100.0
  M_015_NM1_Vorschub_mm_H:
    low: -100.0
    high: 100.0
  D_018_SW_Gesamtverzug_Perc:
    low: -100.0
    high: 100.0
observation_space:
  min_area_weight:
    low: -100.0
    high: 100.0
  unevenness_card_web:
    low: -100.0
    high: 100.0
  tensile_strength_CD:
    low: -100.0
    high: 100.0