actions_are_relative: False
initial_setpoints:
  v_PreRoll: 215.0 # m per min
  v_MainCylinder: 804.0 # m per min
  v_WorkerMain: 40.3 # m per min
  v_WorkerPre: 18.0 # m per min
  CardDeliveryWeightPerArea: 63.0 # g per sqm
  CardDeliverySpeed: 10 # m per min
  Cross-lapperProfiling: 1.0 # percent
  Cross-lapperLayersCount: 4 # -
  DrawFrameDraftRatio: 43.0 # percent
  NeedleloomDraftRatio: 43.0 # percent
  NeedleloomFeedPerStroke: 10.5 # mm per stroke
path_to_dependent_variable_calculations: # use default if not a valid path
dependent_variable_calculations:
  - CardMassThroughput: cardMassThroughputAugsburgCalculation # kg per h
setpoint_bounds:
  v_PreRoll:
    lower: 165.0
    upper: 300.0
  v_MainCylinder:
    lower: 264.0
    upper: 900.0
  v_WorkerMain:
    lower: 30.0
    upper: 120.0
  v_WorkerPre:
    lower: 12.0
    upper: 22.4
  CardDeliveryWeightPerArea:
    lower: 20.0
    upper: 100.0
  CardDeliverySpeed:
    lower: 0.0
    upper: 100.0
  Cross-lapperProfiling:
    lower: 0.0
    upper: 15.0
  Cross-lapperLayersCount:
    lower: 2
    upper: 8
  DrawFrameDraftRatio:
    lower: 0.0
    upper: 100.0
  NeedleloomFeedPerStroke:
    lower: 9.55
    upper: 12.26
  NeedleloomDraftRatio:
    lower: 34.0
    upper: 51.0
dependent_variable_bounds:
  CardMassThroughput:
    lower:
    upper:
  transferRollSafety:
    lower: 30.0
    upper:

